### PR TITLE
chore: rename with new nomenclature

### PR DESCRIPTION
**Pull request by andrewrynhard**
Themes the nomenclature to align with Talos Linux

### CODE REVIEW

**Comment by andrewrynhard** [comment]
Just a draft currently.

**Comment by smira** [comment]
I :heart: factory & schematic, there was also `model`, not sure where it should map?

**Comment by smira** [comment]
(we're in progress of moving to GHA, so CI is somewhat down)

**Comment by andrewrynhard** [comment]
> I ❤️ factory & schematic, there was also `model`, not sure where it should map?

Yeah, I am still working that out but I have some ideas. I think the idea of "A factory that accepts schematics to build a specific model" is the way I am trying to make this work out.

**Comment by andrewrynhard** [comment]
I feel like a "model" is `schematic` + `version`. An `image` is then `model` + `path`. I don't think the API is structured in a way currently that makes these a simple find and replace in this PR but I think that could be a good mental model we can reflect in the API by restructuring it. Alternatively, we could do something like `GET /model/:schematic/:version/:path` (just calling images a model from this point on).

Just thinking out loud here.

**Comment by smira** [comment]
I also feel that "blueprint" might sound nicer than "schematic". I think URLs should reflect what people get - image factory produces images. Or should it be a model factory??.

**Comment by smira** [comment]
(trying to make Drone pick it up)

**Review by smira — APPROVED** [review]

**Pull request merged**
